### ISSUE TITLE
Add a comparison section to the "Why Enhance?" page

### ISSUE THREAD

**Issue by waldyrious** [enhance-dev/enhance.dev#105]
It's great that there's a why/philosophy page in the docs. However, from a cursory look, it wasn't immediately clear how Enhance differs from e.g. Svelte. A comparison section in the [Why Enhance?](https://enhance.dev/docs/learn/why-enhance) page would be helpful in this regard.

**Comment by kristoferjoseph** [comment]
I hear you.

We at Begin do not do comparisons because they are usually a proxy for trashing a perceived competitor for which we have no direct competition.

We like to instead give the reasoning behind our approach and sell it on it's own merits.

What we want is to create a virtuous cycle and leave it up to users to decide what kind of approach they want to take.

**Comment by waldyrious** [comment]
I understand where you're coming from, but I don't think a comparison should necessarily assume or imply a stance of "our approach is better than the others".

I think an objective comparison between relatively similar projects is helpful in allowing people to better understand what this project is about, by building upon mental models they may already have. It's not about advocating for this project's approach over others', but offering a clear view of the various approaches (of a similar vein), so that an informed decision can indeed me made.

Otherwise, users have to build a separate mental model from scratch, which would inevitably vaguely resemble something else they may know; and unless they have a really solid grasp of both systems, they would likely feel confused or unsure about how much of the similarity is real vs misperceived. (I see LitHTML is also mentioned in #100 for similar reasons.)

**Comment by waldyrious** [comment]
Hey @kristoferjoseph I'd love to know if you have any thoughts on what I wrote above.
