### ISSUE TITLE
z-index problem with the mobile navigation

### ISSUE THREAD

**Issue by d2s** [enhance-dev/enhance.dev#130]
When viewed on a mobile device, video controls on the https://enhance.dev/docs/ page get displayed over the site navigation elements.

Screenshot from a Chromium-based browser:

![Screenshot_20230203-175219-02.jpeg](https://user-images.githubusercontent.com/135053/216649302-1ef637ef-157f-4678-b0f8-8a06ce9347fc.jpeg)

Similar is also happening with Firefox Focus browser.

**Comment by tbeseda** [comment]
Hey thanks for filing this and the helpful screenshot, @d2s -- we will definitely look into it.

**Comment by colepeters** [comment]
Fixed on [#1214e93](https://github.com/enhance-dev/enhance.dev/commit/1214e935313b2017c87a5e9e35ad07e07c7d445e). Thanks for the flagging this @d2s!
