### ISSUE TITLE
Front page “code editor” elements horizontal overflow

### ISSUE THREAD

**Issue by fschroiff** [enhance-dev/enhance.dev#149]
The two “code editor” elements on the front page overflow on mobile. 

![IMG_5339](https://user-images.githubusercontent.com/660010/234058170-2681fb38-cc5b-4a3b-af4c-11e1f45cd3a5.jpeg)

**Comment by fschroiff** [comment]
Ah yes, I should have mentioned the browser! Next time 😉

**Comment by colepeters** [comment]
No worries, thanks again! When I saw the screenshot I thought, 'That looks like something iOS Safari would do 😒', haha.

**Comment by colepeters** [comment]
Fixed in https://github.com/enhance-dev/enhance.dev/commit/5a261c647a884fa7d8682d65259828e10a0e23e4
