### ISSUE TITLE
Docs menu background on iOS Safari is transparent

### ISSUE THREAD

**Issue by knowler** [enhance-dev/enhance.dev#173]
Just noticed this while on the docs site on my phone (iOS 17.0.3).

![image](https://github.com/enhance-dev/enhance.dev/assets/6908001/735b5854-c6c9-442c-97e8-2ec4dbda9eab)

**Comment by colepeters** [comment]
Thanks! Looks like this is just happening on dark mode, I'll fix this up today.

**Comment by colepeters** [comment]
Fixed in https://github.com/enhance-dev/enhance.dev/commit/9bb872851ffc4f7f888357a2ae0d292a46125514

Thanks @knowler!

<img width="300" alt="image" src="https://github.com/enhance-dev/enhance.dev/assets/1713932/a714dc26-1b24-48ce-b4ea-438bc2b4de3b">
