### ISSUE TITLE
Docs 404 is missing

### ISSUE THREAD

**Issue by ryanbethel** [enhance-dev/enhance.dev#207]
Missing pages inside docs don't have a 404 page (i.e. [https://enhance.dev/docs/lost](https://enhance.dev/docs/lost) ).

**Comment by macdonst** [comment]
We'd have to ask @colepeters what this code's purpose is as it breaks the above 404 redirect.

https://github.com/enhance-dev/enhance.dev/blob/main/app/api/docs/%24%24.mjs#L67

**Comment by colepeters** [comment]
Great question. This code predates me though so I'm not totally sure myself 😅 

Perhaps one for @tbeseda if not you, Simon? ;)

<img width="960" alt="image" src="https://github.com/enhance-dev/enhance.dev/assets/1713932/4456ade4-1e48-4976-9d35-2a450f474fe6">

**Comment by macdonst** [comment]
@colepeters OMG, this is from the first commit of enhance.dev. Probably worked once upon a time but as the site evolved the bug showed up. I'll take this on.
